from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import JSONFormatter
from flask import request
from flask import Flask
from flask import jsonify

application = Flask(__name__)


@application.route('/', methods=['GET'])
def hello():
    return "wordbook"


@application.route('/multilingual-transcripts/<string:video_id>', methods=['GET'])
def multilingual_transcript_api(video_id):
    transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
    transcript = transcript_list.find_transcript(
        ['en', 'es', 'fr', 'de', 'pt', 'vi', 'hy', 'cs', 'th', 'sw', 'sv', 'fil', 'fi', 'fa', 'ru', "ja"])

    return jsonify(
        video_id=transcript.video_id,
        language=transcript.language,
        language_code=transcript.language_code,
        # whether it has been manually created or generated by YouTube
        is_generated=transcript.is_generated,
        # whether this transcript can be translated or not
        is_translatable=transcript.is_translatable,
        # a list of languages the transcript can be translated to
        translation_languages=transcript.translation_languages,
        transcript=transcript.fetch()
    )


@application.route('/translate-video', methods=['GET'])
def translation_api():
    video_id = request.args.get("vid")
    target_lang = request.args.get("tl")
    transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
    transcript = transcript_list.find_transcript(
        ['en', 'es', 'fr', 'de', 'pt', 'vi', 'hy', 'cs', 'th', 'sw', 'sv', 'fil', 'fi', 'fa', 'ru'])
    translated_transcript = transcript.translate(target_lang)
    formatter = JSONFormatter()
    json_formatted = formatter.format_transcript(translated_transcript.fetch())
    return json_formatted


if __name__ == '__main__':
    application.run(host='0.0.0.0', port=5050)
